// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBH01quHJxizCgz-0fAJJ_YXEYqHaN3ks',
    appId: '1:711267528609:web:a6cf0dac4ed2344df965e0',
    messagingSenderId: '711267528609',
    projectId: 'diyetisyenapp-5765c',
    authDomain: 'diyetisyenapp-5765c.firebaseapp.com',
    storageBucket: 'diyetisyenapp-5765c.appspot.com',
    measurementId: 'G-NL6E9YTV0N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNp7oWWV1P5v2mJi1BUutAUpirkoHzxwM',
    appId: '1:711267528609:android:8648f7f6aee6dbb5f965e0',
    messagingSenderId: '711267528609',
    projectId: 'diyetisyenapp-5765c',
    storageBucket: 'diyetisyenapp-5765c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCK2fM9McQcB-EY-5hkn_t6TuzSmmVqVgo',
    appId: '1:711267528609:ios:353c07ea1f52cf07f965e0',
    messagingSenderId: '711267528609',
    projectId: 'diyetisyenapp-5765c',
    storageBucket: 'diyetisyenapp-5765c.appspot.com',
    iosBundleId: 'com.example.diyetisyenapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCK2fM9McQcB-EY-5hkn_t6TuzSmmVqVgo',
    appId: '1:711267528609:ios:353c07ea1f52cf07f965e0',
    messagingSenderId: '711267528609',
    projectId: 'diyetisyenapp-5765c',
    storageBucket: 'diyetisyenapp-5765c.appspot.com',
    iosBundleId: 'com.example.diyetisyenapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBH01quHJxizCgz-0fAJJ_YXEYqHaN3ks',
    appId: '1:711267528609:web:9ad95870e11263fef965e0',
    messagingSenderId: '711267528609',
    projectId: 'diyetisyenapp-5765c',
    authDomain: 'diyetisyenapp-5765c.firebaseapp.com',
    storageBucket: 'diyetisyenapp-5765c.appspot.com',
    measurementId: 'G-LFXYJ2E3CS',
  );
}
